apiVersion: backend/v1
kind: Config
metadata:
  name: foo-food-backend
build:
  # local:
  #   push: false
  artifacts:
    - image: registry.gitlab.com/svtslv/public/dev-nestjs
      context: .
      docker:
        dockerfile: dev.Dockerfile
      sync:
        manual:
          - src: 'src/**/*.*'
            dest: .
deploy:
  # kubeContext: docker-desktop
  kubectl:
    flags:
      global: [--namespace=nestjs-kubernetes-namespace]
    manifests:
      - ./kubernetes/03-secrets.yaml
      - ./kubernetes/07-data.yaml
      - ./kubernetes/08-nestjs.yaml
